version: '3.9'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3600:3600"
    environment:
      - MONGO_URI=mongodb://mongo:27017/libreria
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
